package main

//go:generate swag init -g cmd/server/main.go --output ./docs --parseDependency --parseInternal

import (
	"log"
	"os"

	// "personalfinancedss/docs" // Not needed - serving swagger.yaml directly
	"personalfinancedss/internal/config"
	"personalfinancedss/internal/fx"
)

// @title Personal Finance DSS API
// @version 1.0
// @description Personal Finance Decision Support System API for managing accounts, transactions, budgets, goals, and investments.
// @termsOfService http://swagger.io/terms/

// @contact.name API Support
// @contact.url http://www.swagger.io/support
// @contact.email support@personalfinancedss.com

// @license.name MIT
// @license.url https://opensource.org/licenses/MIT

// @servers.url http://localhost:8080/api/v1
// @servers.description Development server
// @servers.url https://api.personalfinancedss.com/api/v1
// @servers.description Production server

// @securityDefinitions.apikey BearerAuth
// @in header
// @name Authorization
// @description JWT Authorization header using the Bearer scheme. Enter 'Bearer' [space] and then your token.

func main() {
	log.Println("========================================")
	log.Println("  Personal Finance DSS API Server")
	log.Println("========================================")
	log.Println()

	// Load configuration using Viper
	log.Println("📋 Step 1: Loading configuration...")
	cfg := config.Load()
	log.Println("✅ Configuration loaded successfully")
	log.Println()

	// Validate configuration
	log.Println("🔍 Step 2: Validating configuration...")
	if err := config.ValidateConfig(); err != nil {
		log.Fatalf("❌ Configuration validation failed: %v", err)
		os.Exit(1)
	}
	log.Println("✅ Configuration validated successfully")
	log.Println()

	// Print configuration (excluding sensitive data)
	log.Println("⚙️  Step 3: Configuration Summary")
	config.PrintConfig()
	log.Println()

	// Swagger 2.0 documentation is served directly from swagger.yaml
	log.Println("📚 Step 4: Swagger 2.0 documentation ready")
	log.Println("   - Spec format: Swagger 2.0")
	log.Println("   - Files: swagger.yaml, swagger.json")
	log.Println("   - Generated by: swag v2.0.0")
	log.Println()

	log.Println("🚀 Step 5: Starting application...")
	log.Printf("   Server will be available at: http://%s:%s", cfg.Server.Host, cfg.Server.Port)
	log.Printf("   Swagger: http://%s:%s/swagger/index.html", cfg.Server.Host, cfg.Server.Port)
	log.Printf("   Health: http://%s:%s/health", cfg.Server.Host, cfg.Server.Port)

	if config.IsDevelopment() {
		log.Println("   Mode: DEVELOPMENT 🛠")
	} else {
		log.Println("   Mode: PRODUCTION 🏭")
	}
	log.Println()

	log.Println("📦 Step 6: Initializing dependency injection (Uber FX)...")
	log.Println("   This will initialize: Logger → Database → Router → Services → Handlers")
	log.Println()

	// Create and run FX application - this blocks until interrupted
	// All subsequent logging will be handled by zap logger through FX
	fx.Application().Run()
}
